//=============================================================================
// TDT_DTM.v - JTAG Debug Transport Module (TAP-5 + TDRs + DMI-to-APB bridge)
//=============================================================================
// M7 Task 4. rv906 clone of the donor C906's tdt_dmi_top subsystem (the
// chip-level "JTAG DTM + DMI-to-APB bridge" half of the TDT debug unit).
// The donor splits this across files for its hierarchy; rv906 consolidates
// the chain + idr + apb_master + synchronizers into one self-contained
// module (the rv906 idiom). Section comments below cite the donor file per
// section; line numbers refer to:
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_ctrl.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_chain.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_idr.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_apb_master.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_pulse_sync.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_sync_dff.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi.v
//   refs/openc906/C906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h
//
// Deviations from the donor (design doc 2026-09-11-m7-debug-design.md):
//   D-M7-1  pclk domain IS the SoC core clk (donor's sys_apb_clk); only the
//           tck<->pclk CDC remains, using the donor's own pulse syncs.
//   D-M7-2  4 JTAG pads only (tck/tms/tdi/tdo). The donor's pad_dtm_trst_b,
//           pad_dtm_jtag2_sel, pad_dtm_tap_en pads, the TAP2 custom 2-wire
//           FSM (tdt_dtm_ctrl.v:239-343), and the tms_o/tms_oe/tdo_en pad
//           outputs (tdt_dtm_io.v) are DROPPED. The TAP resets via the
//           standard 5x TMS=1 sequence (IEEE 1149.1) instead of trst_b.
//   D-M7-9  no clock gating: the donor's tdt_gated_clk_cell on apb_pclk
//           (tdt_apb_master.v:254-265) is dropped; the bridge runs on the
//           ungated pclk.
//   D-M7-10 kept: IDCODE 0x10000B6F, DTMCS version=1/abits=10/idle=7,
//           DMI DR {addr[9:0],data[31:0],op[1:0]} LSB-first, the DMI
//           request/response pulse protocol, and the APB FSM shape.
//
// TIMING CONTRACT (tdt_dmi_define.h:301-309): the host must insert
// TDT_DMI_IDLE_CYCLE=7 idle TCK cycles between DMI ops (dtmcs.idle reads
// back 3'h7), and Freq.pclk/Freq.tck > 8/(IDLE_CYCLE-4) = 8/3. The pulse
// synchronizers need pclk edges between tck edges to carry a request
// across; with any pclk/tck ratio meeting 8/3 the worst-case handshake
// (4 dst-FF + 4 src-FF) completes inside the 7-idle-TCK budget.
//
// RESET BEHAVIOR: the tck domain has NO async reset pin (D-M7-2). The TAP
// reaches Test-Logic-Reset after 5+ tck cycles with TMS=1; in TLR the TAP
// holds tdo=1 and the DMI engine is forced idle by the dmihardreset-safe
// initial state. The pclk-domain bridge state resets on preset_n (the SoC's
// tdt_rst_n, D-M7-3). Verilator note: 2-state simulation initializes all
// flops to 0, which matches the donor's post-trst_b state for every tck
// flop except tdo (donor resets tdo to 1 via trst_b) -- so tdo's always
// block explicitly returns to 1 whenever the TAP is not shifting.
//=============================================================================

module TDT_DTM (
    // JTAG pads (D-M7-2: 4 pins, no trst_n)
    input  wire        tck,
    input  wire        tms,
    input  wire        tdi,
    output wire        tdo,

    // pclk domain (in the SoC: pclk = core clk, preset_n = tdt_rst_n)
    input  wire        pclk,
    input  wire        preset_n,

    // APB master to the Debug Module (donor tdt_apb_master.v:36-47 APB side;
    // paddr is the 12-bit byte address {dmi_addr[9:0], 2'b0})
    output wire        apbm_psel,
    output wire        apbm_penable,
    output wire        apbm_pwrite,
    output wire [11:0] apbm_paddr,
    output wire [31:0] apbm_pwdata,
    input  wire        apbm_pready,
    input  wire [31:0] apbm_prdata,
    input  wire        apbm_pslverr
);

    //=========================================================================
    // SECTION: TAP-5 controller state machine
    // Donor tdt_dtm_ctrl.v:93-208 (TAP5_* states and TMS transitions),
    // :213-218 (fsm5_* status decodes). TAP2 (donor :239-343) dropped, D-M7-2.
    // The donor resets the FSM with trst_b/jtag2_sel/dmihardreset (:110-119);
    // rv906 has no trst_n (D-M7-2): the standard 5x TMS=1 sequence reaches
    // TAP5_RESET from any state, and dmihardreset (a tck-domain pulse
    // generated by the DTMCS write below) forces TAP5_RESET like the donor.
    //=========================================================================
    localparam [3:0] TAP5_RESET          = 4'b0000;
    localparam [3:0] TAP5_IDLE           = 4'b0001;
    localparam [3:0] TAP5_SELECT_DR_SCAN = 4'b0011;
    localparam [3:0] TAP5_SELECT_IR_SCAN = 4'b0010;
    localparam [3:0] TAP5_CAPTURE_IR     = 4'b0110;
    localparam [3:0] TAP5_SHIFT_IR       = 4'b0100;
    localparam [3:0] TAP5_EXIT1_IR       = 4'b0101;
    localparam [3:0] TAP5_UPDATE_IR      = 4'b0111;
    localparam [3:0] TAP5_CAPTURE_DR     = 4'b1011;
    localparam [3:0] TAP5_SHIFT_DR       = 4'b1010;
    localparam [3:0] TAP5_EXIT1_DR       = 4'b1000;
    localparam [3:0] TAP5_UPDATE_DR      = 4'b1001;
    localparam [3:0] TAP5_PAUSE_IR       = 4'b1101;
    localparam [3:0] TAP5_EXIT2_IR       = 4'b1111;
    localparam [3:0] TAP5_PAUSE_DR       = 4'b1100;
    localparam [3:0] TAP5_EXIT2_DR       = 4'b1110;

    reg  [3:0] tap5_cur_st;
    reg  [3:0] tap5_nxt_st;

    // dmihardreset is declared with the DTMCS TDR below (tdt_dtm_idr.v:31)
    // but consumed here, exactly like the donor's ctrl (:113-114).
    wire       dmihardreset;

    // TAP5_RESET exits on !tms unconditionally in rv906: the donor gates the
    // exit on io_ctrl_tap_en (tdt_dtm_ctrl.v:126), a pad that rv906 drops
    // (D-M7-2); with the pad dropped the TAP is always enabled.
    always @ (posedge tck) begin
        if (dmihardreset)
            tap5_cur_st[3:0] <= TAP5_RESET;
        else
            tap5_cur_st[3:0] <= tap5_nxt_st[3:0];
    end

    // Donor tdt_dtm_ctrl.v:121-208, transition table verbatim.
    always @ (tap5_cur_st[3:0] or tms) begin
        case (tap5_cur_st[3:0])
            TAP5_RESET:
                if (!tms)     tap5_nxt_st[3:0] = TAP5_IDLE;
                else          tap5_nxt_st[3:0] = TAP5_RESET;
            TAP5_IDLE:
                if (tms)      tap5_nxt_st[3:0] = TAP5_SELECT_DR_SCAN;
                else          tap5_nxt_st[3:0] = TAP5_IDLE;
            TAP5_SELECT_DR_SCAN:
                if (tms)      tap5_nxt_st[3:0] = TAP5_SELECT_IR_SCAN;
                else          tap5_nxt_st[3:0] = TAP5_CAPTURE_DR;
            TAP5_SELECT_IR_SCAN:
                if (!tms)     tap5_nxt_st[3:0] = TAP5_CAPTURE_IR;
                else          tap5_nxt_st[3:0] = TAP5_RESET;
            TAP5_CAPTURE_IR:
                if (!tms)     tap5_nxt_st[3:0] = TAP5_SHIFT_IR;
                else          tap5_nxt_st[3:0] = TAP5_EXIT1_IR;
            TAP5_SHIFT_IR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_EXIT1_IR;
                else          tap5_nxt_st[3:0] = TAP5_SHIFT_IR;
            TAP5_EXIT1_IR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_UPDATE_IR;
                else          tap5_nxt_st[3:0] = TAP5_PAUSE_IR;
            TAP5_PAUSE_IR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_EXIT2_IR;
                else          tap5_nxt_st[3:0] = TAP5_PAUSE_IR;
            TAP5_EXIT2_IR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_UPDATE_IR;
                else          tap5_nxt_st[3:0] = TAP5_SHIFT_IR;
            TAP5_UPDATE_IR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_SELECT_DR_SCAN;
                else          tap5_nxt_st[3:0] = TAP5_IDLE;
            TAP5_CAPTURE_DR:
                if (!tms)     tap5_nxt_st[3:0] = TAP5_SHIFT_DR;
                else          tap5_nxt_st[3:0] = TAP5_EXIT1_DR;
            TAP5_SHIFT_DR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_EXIT1_DR;
                else          tap5_nxt_st[3:0] = TAP5_SHIFT_DR;
            TAP5_EXIT1_DR:
                if (!tms)     tap5_nxt_st[3:0] = TAP5_PAUSE_DR;
                else          tap5_nxt_st[3:0] = TAP5_UPDATE_DR;
            TAP5_PAUSE_DR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_EXIT2_DR;
                else          tap5_nxt_st[3:0] = TAP5_PAUSE_DR;
            TAP5_EXIT2_DR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_UPDATE_DR;
                else          tap5_nxt_st[3:0] = TAP5_SHIFT_DR;
            TAP5_UPDATE_DR:
                if (tms)      tap5_nxt_st[3:0] = TAP5_SELECT_DR_SCAN;
                else          tap5_nxt_st[3:0] = TAP5_IDLE;
            default:          tap5_nxt_st[3:0] = TAP5_RESET;
        endcase
    end

    // Donor tdt_dtm_ctrl.v:213-218 (fsm5_* status decodes; fsm2_* terms
    // dropped with TAP2, D-M7-2 -- the donor ORs the two at :449-457).
    wire shift_ir   = (tap5_cur_st[3:0] == TAP5_SHIFT_IR);
    wire update_ir  = (tap5_cur_st[3:0] == TAP5_UPDATE_IR);
    wire shift_dr   = (tap5_cur_st[3:0] == TAP5_SHIFT_DR);
    wire update_dr  = (tap5_cur_st[3:0] == TAP5_UPDATE_DR);
    wire capture_dr = (tap5_cur_st[3:0] == TAP5_CAPTURE_DR);
    wire capture_ir = (tap5_cur_st[3:0] == TAP5_CAPTURE_IR);

    //=========================================================================
    // SECTION: TDR shift chain (IR + DR shifter, TDO register)
    // Donor tdt_dtm_chain.v:42-48 (opcodes), :56-86 (capture/shift mux,
    // LSB-first), :90-92 (TDI sampled on posedge tck), :109-122 (TDO on
    // negedge tck, idle value 1). The parity register (:98-103) is TAP2-only
    // (ctrl_chain_shift_par is an fsm2 output) -- dropped with TAP2 (D-M7-2).
    //
    // CHAIN_DW = DTM_ABITS + 32 + 2 = 44 (donor tdt_dtm_top.v:41 with
    // DTM_ABITS=10 from tdt_dmi.v:140, TDT_DMI_HIGH_ADDR_W=0 for the single
    // slave, tdt_dmi_define.h:196-197).
    //=========================================================================
    localparam [4:0] IR_IDCODE  = 5'h01;   // tdt_dtm_chain.v:42
    localparam [4:0] IR_DMI_ACC = 5'h02;   // :43
    localparam [4:0] IR_DTMCS   = 5'h10;   // :44
    localparam [4:0] IR_DMI     = 5'h11;   // :45

    localparam       DTM_ABITS    = 10;
    localparam       CHAIN_DW     = 44;    // DTM_ABITS + 32 + 2
    localparam       DMI_DR_W     = 44;    // donor DTM_DMIREG_WIDTH (mode=0)

    reg  [CHAIN_DW-1:0] chain_shifter;
    reg                 tdo_r;

    // idr side (declared with the IDR section below)
    wire [CHAIN_DW-1:0] idr_chain_dr;
    wire [4:0]          idr_chain_ir;
    wire                idr_dmi_mode;

    // Capture/shift mux -- donor tdt_dtm_chain.v:56-86 verbatim (the
    // chain_shifter_pre combinational block). idr_dmi_mode selects the
    // 34-bit DMI_ACC-mode shift (donor :76-79): mode is a DMI_ACC-DR-
    // written flop, kept 1:1 with the donor.
    reg [CHAIN_DW-1:0] chain_shifter_pre;
    always @ (shift_ir or tdi or chain_shifter or capture_dr or
              idr_chain_dr or capture_ir or idr_chain_ir or shift_dr or
              idr_dmi_mode) begin
        chain_shifter_pre[CHAIN_DW-1:0] = {CHAIN_DW{1'b0}};
        if (shift_ir)
            chain_shifter_pre[4:0] = {tdi, chain_shifter[4:1]};
        else if (capture_dr)
            chain_shifter_pre[CHAIN_DW-1:0] = idr_chain_dr[CHAIN_DW-1:0];
        else if (capture_ir)
            chain_shifter_pre[CHAIN_DW-1:0] = {{CHAIN_DW-5{1'b0}}, idr_chain_ir[4:0]};
        else if (shift_dr)
            case (idr_chain_ir[4:0])
                IR_DMI_ACC : chain_shifter_pre[0] = tdi;                       // 1 bit bypass
                IR_DMI     : if (idr_dmi_mode)
                                 chain_shifter_pre[CHAIN_DW-DTM_ABITS-1:0] =   // 34 bits
                                     {tdi, chain_shifter[CHAIN_DW-DTM_ABITS-1:1]};
                             else
                                 chain_shifter_pre[DMI_DR_W-1:0] =             // 44 bits
                                     {tdi, chain_shifter[DMI_DR_W-1:1]};
                IR_DTMCS   : chain_shifter_pre[31:0] = {tdi, chain_shifter[31:1]};
                IR_IDCODE  : chain_shifter_pre[31:0] = {tdi, chain_shifter[31:1]};
                default    : chain_shifter_pre[0] = tdi;                       // 1 bit bypass
            endcase
        else
            chain_shifter_pre[CHAIN_DW-1:0] = chain_shifter[CHAIN_DW-1:0];
    end

    // Data shifts from the lowest bit; TDI sampled on posedge tck
    // (donor tdt_dtm_chain.v:88-92). No reset: the shifter's value only
    // matters after a Capture, which overwrites it.
    always @ (posedge tck) begin
        chain_shifter[CHAIN_DW-1:0] <= chain_shifter_pre[CHAIN_DW-1:0];
    end

    wire [CHAIN_DW-1:0] chain_idr_data = chain_shifter[CHAIN_DW-1:0];

    // TDO: negedge-tck register, logic 1 when not shifting (donor
    // tdt_dtm_chain.v:105-122). The donor's async trst_b reset arm is
    // replaced by the dmihardreset arm (donor :112-113) plus the plain
    // "else tdo<=1" fallthrough: with the TAP in TLR/IDLE (or any non-shift
    // state) tdo always returns to 1, which covers the no-trst_n power-up
    // case in 2-state simulation as well.
    always @ (negedge tck) begin
        if (dmihardreset)
            tdo_r <= 1'b1;
        else if (shift_dr || shift_ir)
            tdo_r <= chain_shifter[0];
        else
            tdo_r <= 1'b1;
    end

    assign tdo = tdo_r;

    //=========================================================================
    // SECTION: TDRs (IDCODE / DTMCS / DMI / DMI_ACC) + DMI request engine
    // Donor tdt_dtm_idr.v whole file. Registers: dtm_ir (:69-77),
    // dmihardreset (:86-93), dmireset (:95-104), mode (:106-113),
    // address (:115-122), data (:124-134), op (:136-143), wr_vld (:145-155),
    // dmi_req_running (:157-166), op_stat (:170-180), read mux (:192-208).
    // The donor's async trst_b reset arms are dropped (D-M7-2: no trst_n);
    // every register's dmihardreset arm is kept, and the DTMCS.dmihardreset
    // write bit provides the in-band reset the spec requires. In 2-state
    // simulation all flops power up 0, which is exactly the donor's
    // post-trst state for these registers except dtm_ir (donor resets the IR
    // to IDCODE) -- mirrored below by TLR: see the dtm_ir comment.
    //=========================================================================
    localparam [31:0] IDCODE_REG_DEFINE = {4'h1, 16'h0, 12'b1011_011_0111_1}; // :45 = 32'h1000_0B6F
    localparam [3:0]  DTM_VERSION       = 4'h1;                                // :46 (dtmcs.version=1, spec 0.13)
    localparam [2:0]  IDLE_CYCLE        = 3'h7;                                // :47 = `TDT_DMI_IDLE_CYCLE (tdt_dmi_define.h:309)

    reg  [4:0]          dtm_ir;
    reg                 dmihardreset_r;
    reg                 dmireset;
    reg                 mode;
    reg  [DTM_ABITS-1:0] address;
    reg  [31:0]         data;
    reg  [1:0]          op;
    reg  [1:0]          op_stat;
    reg                 wr_vld;
    reg                 dmi_req_running;

    wire                apbm_dtm_wr_ready_tck;   // ready pulse synced pclk->tck
    wire [31:0]         apbm_dtm_rdata;          // held-stable read data from the bridge

    // IR register -- donor tdt_dtm_idr.v:69-77. The donor's trst_b arm loads
    // IDCODE; per IEEE 1149.1 Test-Logic-Reset must also load IDCODE (or
    // BYPASS) so a fresh TAP is scannable without trst_n. rv906 adds the
    // TAP5_RESET arm (loads IDCODE) precisely to recover that power-up
    // behavior that trst_b provided -- the standard-mandated TLR behavior,
    // noted here as the deliberate no-trst_n compensation (D-M7-2).
    always @ (posedge tck) begin
        if (tap5_cur_st[3:0] == TAP5_RESET)
            dtm_ir[4:0] <= IR_IDCODE;
        else if (dmihardreset)
            dtm_ir[4:0] <= IR_IDCODE;
        else if (update_ir)
            dtm_ir[4:0] <= chain_idr_data[4:0];
    end

    // dtmcs fields (donor :81-84)
    wire [1:0] dmistat = op_stat[1:0];

    // dmihardreset: 1-tck pulse on a DTMCS write with bit 17 set
    // (donor :86-93). Resets the DMI bridge (via the tck->pclk pulse sync
    // below) and, in the SoC, the DM's DMI-side hard reset.
    always @ (posedge tck) begin
        if (dmihardreset_r)
            dmihardreset_r <= 1'b0;
        else if (update_dr && dtm_ir[4:0] == IR_DTMCS)
            dmihardreset_r <= chain_idr_data[17];
    end
    assign dmihardreset = dmihardreset_r;

    // dmireset: 1-tck pulse on a DTMCS write with bit 16 set (donor :95-104);
    // clears the DMI request engine (op_stat below).
    always @ (posedge tck) begin
        if (dmihardreset)
            dmireset <= 1'b0;
        else if (dmireset)
            dmireset <= 1'b0;
        else if (update_dr && dtm_ir[4:0] == IR_DTMCS)
            dmireset <= chain_idr_data[16];
    end

    // mode (DMI_ACC DR bit 0) -- donor :106-113. Kept 1:1 with the donor even
    // though rv906's bench only uses mode=0 (the 44-bit DMI shift).
    always @ (posedge tck) begin
        if (dmihardreset)
            mode <= 1'b0;
        else if (update_dr && dtm_ir[4:0] == IR_DMI_ACC)
            mode <= chain_idr_data[0];
    end

    // DMI request payload registers -- donor :115-143. The payload is held
    // stable while a request is in flight (the !dmi_req_running guards);
    // that stability is the donor's CDC contract (the multi-bit payload is
    // sampled on the synchronized request pulse in the pclk domain --
    // tdt_apb_master.v:94-100 -- with no per-bit sync, so it must not move
    // until apbm_dtm_wr_ready returns; donor assertions :218-243).
    always @ (posedge tck) begin
        if (dmihardreset)
            address[DTM_ABITS-1:0] <= {DTM_ABITS{1'b0}};
        else if (update_dr && !mode && dtm_ir[4:0] == IR_DMI && !dmi_req_running)
            address[DTM_ABITS-1:0] <= chain_idr_data[34 +: DTM_ABITS];
    end

    always @ (posedge tck) begin
        if (dmihardreset)
            data[31:0] <= 32'h0;
        else if (update_dr && dtm_ir[4:0] == IR_DMI && !dmi_req_running)
            data[31:0] <= chain_idr_data[33:2];
        else if (apbm_dtm_wr_ready_tck && op[1:0] == 2'b01)
            data[31:0] <= apbm_dtm_rdata[31:0];
    end

    always @ (posedge tck) begin
        if (dmihardreset)
            op[1:0] <= 2'b0;
        else if (update_dr && dtm_ir[4:0] == IR_DMI && !dmi_req_running)
            op[1:0] <= chain_idr_data[1:0];
    end

    // DMI request pulse: fires on UPDATE_DR with a legal op (read=01 or
    // write=10; ^chain_idr_data[1:0] is exactly "01 or 10") while idle
    // (donor :145-155). 1-tck pulse; crosses to pclk via the pulse sync.
    always @ (posedge tck) begin
        if (dmihardreset)
            wr_vld <= 1'b0;
        else if (wr_vld)
            wr_vld <= 1'b0;
        else if (update_dr && dtm_ir[4:0] == IR_DMI && (^chain_idr_data[1:0])
                 && op_stat[1:0] == 2'b0 && !dmi_req_running)
            wr_vld <= 1'b1;
    end

    // In-flight flag (donor :157-166): set by the request pulse, cleared by
    // the returning ready pulse.
    always @ (posedge tck) begin
        if (dmihardreset)
            dmi_req_running <= 1'b0;
        else if (apbm_dtm_wr_ready_tck)
            dmi_req_running <= 1'b0;
        else if (wr_vld)
            dmi_req_running <= 1'b1;
    end

    // A capture of the DMI DR while a request is in flight reports busy.
    wire capture_dmi_in_running = dmi_req_running && capture_dr && dtm_ir[4:0] == IR_DMI;

    // op_stat (surfaced as dtmcs.dmistat) -- donor :170-180: 2'b11 busy if a
    // new op is scanned while a request runs, or if the DMI DR is captured
    // mid-flight. dmireset clears it (the spec's recovery path).
    always @ (posedge tck) begin
        if (dmihardreset)
            op_stat[1:0] <= 2'b0;
        else if (dmireset)
            op_stat[1:0] <= 2'b0;
        else if ((dmi_req_running && update_dr && dtm_ir[4:0] == IR_DMI && (^chain_idr_data[1:0]))
                 || capture_dmi_in_running)
            op_stat[1:0] <= 2'b11;
    end

    // DMI DR read value (donor :182): mid-flight capture reports op=2'b11
    // (busy) on the wire; otherwise the stored op_stat.
    wire [CHAIN_DW-1:0] dmi_total = capture_dmi_in_running
        ? {address[DTM_ABITS-1:0], data[31:0], 2'b11}
        : {address[DTM_ABITS-1:0], data[31:0], op_stat[1:0]};

    // DR read mux (donor :192-208). Unknown IR (default) reads all-zero from
    // idr_chain_dr, but the chain's shift path for a non-listed IR is the
    // 1-bit bypass (tdt_dtm_chain.v:82) -- so unknown IRs behave as BYPASS,
    // matching the donor exactly.
    reg [CHAIN_DW-1:0] data_out;
    always @ (dtm_ir or mode or dmistat or dmi_total) begin
        case (dtm_ir[4:0])
            IR_IDCODE  : data_out[CHAIN_DW-1:0] = {{CHAIN_DW-32{1'b0}}, IDCODE_REG_DEFINE[31:0]};
            IR_DMI_ACC : data_out[CHAIN_DW-1:0] = {{CHAIN_DW-1{1'b0}}, mode};
            IR_DTMCS   : data_out[CHAIN_DW-1:0] = {{CHAIN_DW-15{1'b0}}, IDLE_CYCLE[2:0],
                                                   dmistat[1:0], 6'd10, DTM_VERSION[3:0]};
            IR_DMI     : data_out[CHAIN_DW-1:0] = dmi_total[CHAIN_DW-1:0];
            default    : data_out[CHAIN_DW-1:0] = {CHAIN_DW{1'b0}};
        endcase
    end

    assign idr_dmi_mode              = mode;
    assign idr_chain_dr[CHAIN_DW-1:0] = data_out[CHAIN_DW-1:0];
    assign idr_chain_ir[4:0]         = dtm_ir[4:0];

    //=========================================================================
    // SECTION: DMI-to-APB bridge
    // Donor tdt_apb_master.v whole file + the two tdt_dmi_pulse_sync
    // instances (:55-71 for cmd_vld/dmihardreset tck->pclk, :241-248 for
    // apb_wr_ready pclk->tck). The donor's clock-gating cell (:254-265) is
    // dropped (D-M7-9); the bridge FSM runs on ungated pclk. pslverr is
    // consumed-but-ignored exactly like the donor (tdt_apb_master.v declares
    // the input and never reads it -- an APB error completes the transaction
    // normally and the DM's own error handling applies); mirrored here and
    // documented so the input is not silently dangling.
    //=========================================================================

    //--- Pulse synchronizers (donor tdt_dmi_pulse_sync.v, instantiated
    //    three times in tdt_apb_master.v:55-71,241-248) ---
    wire cmd_vld_sync;
    wire dmihardreset_sync;
    wire apb_wr_ready_pclk_d1;

    tdt_dmi_pulse_sync x_sync_cmd_vld (
        .src_clk   (tck),
        .dst_clk   (pclk),
        .src_rst_b (preset_n),        // no trst_n (D-M7-2): the tck side of the
        .dst_rst_b (preset_n),        // sync is reset by preset_n (tdt_rst_n)
        .src_pulse (wr_vld),
        .dst_pulse (cmd_vld_sync)
    );

    tdt_dmi_pulse_sync x_sync_dmihardreset (
        .src_clk   (tck),
        .dst_clk   (pclk),
        .src_rst_b (preset_n),
        .dst_rst_b (preset_n),
        .src_pulse (dmihardreset),
        .dst_pulse (dmihardreset_sync)
    );

    tdt_dmi_pulse_sync x_sync_apb_wr_ready (
        .src_clk   (pclk),
        .dst_clk   (tck),
        .src_rst_b (preset_n),
        .dst_rst_b (preset_n),        // no trst_n (D-M7-2): the tck side of the
        .src_pulse (apb_wr_ready_pclk_d1),  // ready sync is reset by preset_n
        .dst_pulse (apbm_dtm_wr_ready_tck)
    );

    //--- Payload capture (donor :72-100): sampled on the synced request
    //    pulse; held stable by the tck-side guards above ---
    reg  [1:0]          wr_flg_smp;
    reg  [DTM_ABITS-1:0] addr_smp;
    reg  [31:0]         wdata_smp;

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n) begin
            wr_flg_smp[1:0]          <= 2'b0;
            addr_smp[DTM_ABITS-1:0]  <= {DTM_ABITS{1'b0}};
            wdata_smp[31:0]          <= 32'b0;
        end else if (dmihardreset_sync) begin
            wr_flg_smp[1:0]          <= 2'b0;
            addr_smp[DTM_ABITS-1:0]  <= {DTM_ABITS{1'b0}};
            wdata_smp[31:0]          <= 32'b0;
        end else if (cmd_vld_sync) begin
            wr_flg_smp[1:0]          <= op[1:0];
            addr_smp[DTM_ABITS-1:0]  <= address[DTM_ABITS-1:0];
            wdata_smp[31:0]          <= data[31:0];
        end
    end

    //--- APB master FSM (donor :102-162). trans_req = cmd_vld_sync_dly &
    //    (read-or-write op) & addr legal; single slave => addr always legal
    //    (donor :122-126, TDT_DMI_SINGLE_SLAVE defined at
    //    tdt_dmi_define.h:154-157) ---
    localparam [1:0] APB_IDLE   = 2'b00;
    localparam [1:0] APB_SETUP  = 2'b01;
    localparam [1:0] APB_ACCESS = 2'b10;

    reg  [1:0] p_state;
    reg  [1:0] n_state;
    reg        cmd_vld_sync_dly;

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            cmd_vld_sync_dly <= 1'b0;
        else if (dmihardreset_sync)
            cmd_vld_sync_dly <= 1'b0;
        else
            cmd_vld_sync_dly <= cmd_vld_sync;
    end

    wire trans_req = cmd_vld_sync_dly & (wr_flg_smp[0] ^ wr_flg_smp[1]);

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            p_state[1:0] <= APB_IDLE;
        else if (dmihardreset_sync)
            p_state[1:0] <= APB_IDLE;
        else
            p_state[1:0] <= n_state[1:0];
    end

    // Donor :140-162 verbatim (back-to-back transactions: pready & trans_req
    // in APB_ACCESS goes straight to APB_SETUP for the next op).
    always @ (p_state or apbm_pready or trans_req) begin
        case (p_state[1:0])
            APB_IDLE:
                if (trans_req)  n_state[1:0] = APB_SETUP;
                else            n_state[1:0] = APB_IDLE;
            APB_SETUP:          n_state[1:0] = APB_ACCESS;
            APB_ACCESS:
                if (apbm_pready && trans_req)       n_state[1:0] = APB_SETUP;
                else if (apbm_pready && !trans_req) n_state[1:0] = APB_IDLE;
                else                                n_state[1:0] = APB_ACCESS;
            default:            n_state[1:0] = APB_IDLE;
        endcase
    end

    // psel / penable / pwrite / paddr / pwdata registered outputs
    // (donor :164-211). paddr = {addr, 2'b0} -- the DMI word address as a
    // byte address (donor :208).
    reg psel_r, penable_r, pwrite_r;
    reg [11:0] paddr_r;
    reg [31:0] pwdata_r;

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            psel_r <= 1'b0;
        else if (dmihardreset_sync)
            psel_r <= 1'b0;
        else if (p_state[1:0] == APB_IDLE && trans_req)
            psel_r <= 1'b1;
        else if (p_state[1:0] == APB_ACCESS && apbm_pready && !trans_req)
            psel_r <= 1'b0;
    end

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            penable_r <= 1'b0;
        else if (dmihardreset_sync)
            penable_r <= 1'b0;
        else if (p_state[1:0] == APB_SETUP)
            penable_r <= 1'b1;
        else if (p_state[1:0] == APB_ACCESS && apbm_pready)
            penable_r <= 1'b0;
    end

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n) begin
            pwrite_r        <= 1'b0;
            paddr_r[11:0]   <= 12'b0;
            pwdata_r[31:0]  <= 32'b0;
        end else if (dmihardreset_sync) begin
            pwrite_r        <= 1'b0;
            paddr_r[11:0]   <= 12'b0;
            pwdata_r[31:0]  <= 32'b0;
        end else if (trans_req) begin
            pwrite_r        <= wr_flg_smp[1];
            paddr_r[11:0]   <= {addr_smp[DTM_ABITS-1:0], 2'b0};
            pwdata_r[31:0]  <= wdata_smp[31:0];
        end
    end

    // Completion: pready & penable (donor :213-228), delayed one pclk cycle
    // then pulse-synced back to tck.
    wire apb_wr_ready_pclk = apbm_pready & penable_r;
    reg  apb_wr_ready_pclk_d1_r;

    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            apb_wr_ready_pclk_d1_r <= 1'b0;
        else if (dmihardreset_sync)
            apb_wr_ready_pclk_d1_r <= 1'b0;
        else if (apb_wr_ready_pclk_d1_r)
            apb_wr_ready_pclk_d1_r <= 1'b0;
        else if (apb_wr_ready_pclk)
            apb_wr_ready_pclk_d1_r <= 1'b1;
    end
    assign apb_wr_ready_pclk_d1 = apb_wr_ready_pclk_d1_r;

    // Read data captured at completion and HELD (donor :230-251): crosses
    // back to tck as a stable multi-bit value sampled when the ready pulse
    // arrives in the tck domain (same held-stable contract as the request
    // payload).
    reg [31:0] prdata_smp;
    always @ (posedge pclk or negedge preset_n) begin
        if (!preset_n)
            prdata_smp[31:0] <= 32'b0;
        else if (dmihardreset_sync)
            prdata_smp[31:0] <= 32'b0;
        else if (apb_wr_ready_pclk)
            prdata_smp[31:0] <= apbm_prdata[31:0];
    end

    assign apbm_dtm_rdata[31:0] = prdata_smp[31:0];

    assign apbm_psel    = psel_r;
    assign apbm_penable = penable_r;
    assign apbm_pwrite  = pwrite_r;
    assign apbm_paddr   = paddr_r;
    assign apbm_pwdata  = pwdata_r;

    // pslverr: declared input, intentionally unused -- mirrors the donor
    // (tdt_apb_master.v:43 declares pslverr and never reads it). The DM
    // never raises it; if it ever did, the transaction completes normally.
    wire unused_pslverr = apbm_pslverr;

endmodule

//=============================================================================
// tdt_dmi_pulse_sync -- toggle 4-FF pulse synchronizer
// Donor tdt_dmi_pulse_sync.v verbatim (the "4-FF handshake": the source
// pulse sets a level that holds until the destination's edge-detected
// acknowledge crosses back, guaranteeing exactly one destination pulse per
// source pulse even with no reset on one side -- rv906 resets both sides
// from preset_n since there is no trst_n, D-M7-2).
//=============================================================================
module tdt_dmi_pulse_sync #(
    parameter SYNC_NUM = 2
)(
    input  wire src_clk,
    input  wire dst_clk,
    input  wire src_rst_b,
    input  wire dst_rst_b,
    input  wire src_pulse,
    output wire dst_pulse
);
    reg  src_pulse_2_lvl;
    wire dst_lvl;
    reg  dst_lvl_d;
    wire dst_lvl_src;
    reg  dst_lvl_src_d;
    wire dst_pulse_2_src;

    always @ (posedge src_clk or negedge src_rst_b) begin
        if (!src_rst_b)
            dst_lvl_src_d <= 1'b0;
        else
            dst_lvl_src_d <= dst_lvl_src;
    end

    assign dst_pulse_2_src = dst_lvl_src & ~dst_lvl_src_d;

    always @ (posedge src_clk or negedge src_rst_b) begin
        if (!src_rst_b)
            src_pulse_2_lvl <= 1'b0;
        else if (dst_pulse_2_src)
            src_pulse_2_lvl <= 1'b0;
        else if (src_pulse)
            src_pulse_2_lvl <= 1'b1;
    end

    tdt_dmi_sync_dff #(
        .SYNC_NUM (SYNC_NUM)
    ) x_tdt_dmi_sync_dff (
        .dst_clk   (dst_clk),
        .dst_rst_b (dst_rst_b),
        .src_in    (src_pulse_2_lvl),
        .dst_out   (dst_lvl)
    );

    tdt_dmi_sync_dff #(
        .SYNC_NUM (SYNC_NUM)
    ) x_tdt_dmi_sync_dff_back (
        .dst_clk   (src_clk),
        .dst_rst_b (src_rst_b),
        .src_in    (dst_lvl),
        .dst_out   (dst_lvl_src)
    );

    always @ (posedge dst_clk or negedge dst_rst_b) begin
        if (!dst_rst_b)
            dst_lvl_d <= 1'b0;
        else
            dst_lvl_d <= dst_lvl;
    end

    assign dst_pulse = dst_lvl & ~dst_lvl_d;

endmodule

//=============================================================================
// tdt_dmi_sync_dff -- SYNC_NUM-deep 2-FF synchronizer chain
// Donor tdt_dmi_sync_dff.v verbatim.
//=============================================================================
module tdt_dmi_sync_dff #(
    parameter SYNC_NUM = 2
)(
    input  wire dst_clk,
    input  wire dst_rst_b,
    input  wire src_in,
    output wire dst_out
);
    reg [SYNC_NUM-1:0] sync_ff;

    always @ (posedge dst_clk or negedge dst_rst_b) begin
        if (!dst_rst_b)
            sync_ff[SYNC_NUM-1:0] <= {SYNC_NUM{1'b0}};
        else
            sync_ff[SYNC_NUM-1:0] <= {sync_ff[SYNC_NUM-2:0], src_in};
    end

    assign dst_out = sync_ff[SYNC_NUM-1];

endmodule
