#!/bin/bash
# test/m6/run_linux.sh -- M6 Linux boot acceptance (Task 8).
#
# Boots the prebuilt OpenSBI 1.3 fw_jump + Linux 6.5 + 5MB initrd
# through the full RTL:
#
#   fw_jump.elf   elf[0], entry 0x80000000 == reset vector (M-mode SBI)
#   Image         --kernel, raw @ 0x80200000 == fw_jump _jump_addr (S)
#   rootfs.cpio   --initrd, raw @ 0x84000000
#
# The DTB is auto-generated by the harness and placed at 0x82200000
# (fw_jump's fixed fw_next_arg1 -- verified by disassembly of the
# shipped fw_jump.elf; the harness dtb_addr must match, Task 8).
#
# Gating marker: "Linux version" (kernel earlycon banner).
# Informational markers (not gating):
#   "OpenSBI"     -- M->S transition reached
#   "Run /init"   -- userspace init reached (stretch)
#
# The M1 ISS checker runs by default (checker=1) -- a free validation
# net. If it has an interrupt-modeling gap (first real interrupts),
# re-run with NO_CHECKER=1 and record the outcome.
#
# Usage:
#   bash test/m6/run_linux.sh                  # 6h wall cap, checker on
#   LINUX_TIMEOUT=7200 NO_CHECKER=1 bash test/m6/run_linux.sh
# Exit 0 iff the gating marker appears in the log.

cd "$(dirname "$0")/../.."

PREBUILT=/home/vlsilab/zhouz/workspace/C2RTL/rvproc/RVProc6/vla/rvvla/test/llm_demo/prebuilt/linux
FW=$PREBUILT/fw_jump.elf
IMAGE=$PREBUILT/Image
INITRD=$PREBUILT/rootfs.cpio
for f in $FW $IMAGE $INITRD; do
    [ -r "$f" ] || { echo "run_linux.sh: missing $f" >&2; exit 2; }
done

TIMEOUT=${LINUX_TIMEOUT:-21600}
CHECKER_ARGS=""
[ "${NO_CHECKER:-0}" = "1" ] && CHECKER_ARGS="--no-checker"
LOG=test/m6/boot.log
mkdir -p test/m6

echo "boot: timeout=${TIMEOUT}s checker=${NO_CHECKER:-on} fw=$(basename "$FW")"
timeout "$TIMEOUT" bin/verisim/testbench $CHECKER_ARGS \
    "$FW" --kernel "$IMAGE" --initrd "$INITRD" > "$LOG" 2>&1
rc=$?

echo "--- markers (log: $LOG) ---"
grep -m1 "OpenSBI"     "$LOG" || echo "(no OpenSBI banner)"
grep -m1 "Linux version" "$LOG" || echo "(no Linux banner)"
grep -m1 "Run /init"   "$LOG" || echo "(no Run /init)"
echo "timeout rc=$rc (124 = wall cap hit)"

if grep -q "Linux version" "$LOG"; then
    echo "BOOT-PASS"
    exit 0
fi
echo "BOOT-FAIL"
exit 1
